# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
    default:
        cmds:
        - echo "{{.GREETING}}"
    test:
        cmds:
            - go test -timeout 30s -v ./...
